#!/usr/bin/with-contenv bash

# create folders
mkdir -p \
	/config/{data,uploads}

# make symlinks
[[ ! -e /var/www/localhost/lychee ]] && \
	ln -s /usr/share/webapps/lychee /var/www/localhost/lychee
  ln -s /usr/share/webapps/lychee/data /config/cache/data
  ln -s /usr/share/webapps/lychee/uploads /config/cache/uploads

# permissions
chown -R abc:abc \
	/config \
	/usr/share/webapps/lychee \
	var/www/localhost/lychee
